### ISSUE TITLE
Regression in list height while dragging in 10.1.0

### ISSUE THREAD

**Issue by ianschmitz** [atlassian/react-beautiful-dnd#1162]
## Bug or feature request?

Bug

### Expected behavior
List height is maintained when drag begins

### Actual behavior
List height shrinks equal to the amount of one item

### Steps to reproduce
I am using a portal for the currently dragging item setup as described in the docs. 

When looking at the DOM i notice that prior to 16.1.0, when i began dragging, a dummy div was inserted in the list in place of the dragging item. In 16.1.0 there is no longer a dummy div inserted and therefore the height of the list shrinks by one item height. If i revert back to 10.0.4 everything works as expected.

### What version of `React` are you using?
16.8.4

### What version of `react-beautiful-dnd` are you running?
16.1.0

### What browser are you using?
Latest chrome

### Demo
Here is a visual example:
![adjustmentOfItems](https://user-images.githubusercontent.com/6355370/54243900-7dc97680-44e7-11e9-8b23-01584321a104.gif)

**Comment by alexreardon** [comment]
have a look at your console. do you see anything?

**Comment by alexreardon** [comment]
I suspect you are not inserting the `droppableProvided.placeholder`

**Comment by alexreardon** [comment]
Also, your app looks cool! Is it public? I would like to take a look

**Comment by alexreardon** [comment]
https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/api/droppable.md#1-provided-droppableprovided

**Comment by ianschmitz** [comment]
That was absolutely it. I hadn't added the `provided.placeholder`. Not sure how it was working before but oh well! Thank you very much for the quick response. I also noticed https://codesandbox.io/s/k260nyxq9v doesn't include `provided.droppableProps`. Not sure if this is an oversight?

We just released 1.0: https://apps.geocortex.com/webviewer/designer/

**Comment by alexreardon** [comment]
Home lists got away with not inserting the placeholder before because it was not used in the same way.

It was an oversight. I have updated the example

**Comment by alexreardon** [comment]
I am glad it was an easy fix!

**Comment by spencerkingman-niche** [comment]
Updating my `react-dom` dependency from 16.1.2 to 16.4.2 made the `provided.placeholder` start rendering for me. I am on `react` 16.6.3 and `react-beautiful-dnd` 10.1.1.

**Comment by ColadaFF** [comment]
I have an older version on rb-dnd@8, and this behaviour is happening, because the placeholder is returning always null, even when dragging some child, Is this issue not solved in the 8 version?
